# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: kubernetes-example-registry
# type: kubernetes.io/dockerconfigjson
# stringData:
#   # Create a Deploy Token in GitLab (Settings -> Respository -> Exapand "Deploy tokens")
#   # with "read_registry" capabilities. Put in a username, that you also put below. Put the
#   # token as password below. For the auth value, run:
#   # $ echo -n "username:password" | base 64
#   # where you replace username and password for the respective values.
#   .dockerconfigjson: |
#     {
#       "auths": {
#         "gitlab.lrz.de:5005/ldv/teaching/ami/ami2023/projects/group00": {
#           "username": "k8s",
#           "password": "EvsSSuu-SifZNdJjr17J",
#           "email": "simon.schumann@tum.de",
#           "auth": "azhzOkV2c1NTdXUtU2lmWk5kSmpyMTdK"
#         }
#       }
#     }
---   
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-example-registry
type: kubernetes.io/dockerconfigjson
stringData:
  # Create a Deploy Token in GitLab (Settings -> Respository -> Exapand "Deploy tokens")
  # with "read_registry" capabilities. Put in a username, that you also put below. Put the
  # token as password below. For the auth value, run:
  # $ echo -n "username:password" | base 64
  # where you replace username and password for the respective values.
  .dockerconfigjson: |
    {
      "auths": {
        "gitlab.lrz.de:5005/ldv/teaching/ami/ami2023/projects/group02": {
          "username": "app_deployment",
          "password": "e4j3VZXsbKksbyEUir19",
          "email": "huixu.liu@tum.de",
          "auth": "YXBwX2RlcGxveW1lbnQ6ZTRqM1ZaWHNiS2tzYnlFVWlyMTk="
        }
      }
    }
